template: "Mandatory field" #https://github.com/release-drafter/release-drafter/blob/master/bin/generate-schema.js#L15
autolabeler:
  - label: 'build'
    title:
      - '/^build(\(.+\))?: /i'
  - label: 'fix'
    title:
      - '/^fix(\(.+\))?: /i'
  - label: 'feat'
    title:
      - '/^feat(\(.+\))?: /i'
  - label: 'docs'
    title:
      - '/^docs(\(.+\))?: /i'
  - label: 'chore'
    title:
      - '/^chore(\(.+\))?: /i'
  - label: 'ci'
    title:
      - '/^ci(\(.+\))?: /i'
  - label: 'perf'
    title:
      - '/^perf(\(.+\))?: /i'
  - label: 'refactor'
    title:
      - '/^refactor(\(.+\))?: /i'
  - label: 'revert'
    title:
      - '/^revert(\(.+\))?: /i'
  - label: 'style'
    title:
      - '/^style(\(.+\))?: /i'
  - label: 'test'
    title:
      - '/^test(\(.+\))?: /i'
