repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    -   id: trailing-whitespace
        name: Trailing Whitespace Checker
        entry: trailing-whitespace
        files: .
        fail_fast: true