version: "3.8"
services:

  relay:
    image: "ghcr.io/denostr-lab/denostr:v2"
    environment:
      PORT: 7447
      POSTGRESQL_DATABASE: postgres://nostr:nostr@postgres:5432/nostr?sslmode=disable
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - 2700:7447

  postgres:
    image: "postgres:15-alpine"
    restart: always
    environment:
      POSTGRES_DB: nostr
      POSTGRES_USER: nostr
      POSTGRES_PASSWORD: nostr
      POSTGRES_HOST_AUTH_METHOD: trust # allow all connections without a password. This is *not* recommended for prod
      PGDATA: /data/postgres
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U nostr"] # database username here - nostr, should be changed if other user
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/data/postgres

volumes:
  postgres_data:
