---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: denostr
  name: denostr-static-mirroring-statefulset
  labels:
    component: denostr
spec:
  serviceName: denostr-svc
  replicas: 3
  selector:
    matchLabels:
      component: denostr
  template:
    metadata:
      labels:
        component: denostr
    spec:
      imagePullSecrets:
        - name: ghcr
      containers:
        - name: relay
          image: ghcr.io/denostr-lab/denostr:v0.2.1-static-mirroring
          imagePullPolicy: Always
          resources:
            requests:
              cpu: "100m"
              memory: "100Mi"
            limits:
              cpu: "500m"
              memory: "500Mi"
          env:
            - name: MONGO_URI
              value: "mongodb://user:pass@host:port/db?replicaSet=rs0&authSource=admin"
          ports:
            - containerPort: 8008
              name: ws
          volumeMounts:
            - mountPath: /app/.nostr
              name: denostr-static-mirroring-config-val
      volumes:
        - name: denostr-config-val
          configMap:
            name: denostr-worker-config
            items:
            - key: settings.yaml
              path: settings.yaml
