---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: denostr
  name: denostr-relay-worker
  labels:
    app: denostr
    component: relay-worker
spec:
  serviceName: denostr-relay-worker-svc
  replicas: 1
  selector:
    matchLabels:
      app: denostr
      component: relay-worker
  template:
    metadata:
      labels:
        app: denostr
        component: relay-worker
    spec:
      imagePullSecrets:
        - name: ghcr
      containers:
        - name: relay
          image: ghcr.io/denostr-lab/denostr:v0.2.4-worker
          imagePullPolicy: Always
          resources:
            requests:
              cpu: "100m"
              memory: "100Mi"
            limits:
              cpu: "300m"
              memory: "500Mi"
          env:
            - name: DEBUG
              value: "*"
            - name: MONGO_URI
              value: "mongodb://user:pass@host:port/db?replicaSet=rs0&authSource=admin"
          ports:
            - containerPort: 8008
              name: ws
          volumeMounts:
            - mountPath: /app/.nostr
              name: denostr-config-vol
      volumes:
        - name: denostr-config-val
          configMap:
            name: denostr-relay-config
            items:
              - key: settings.yaml
                path: settings.yaml
