name: CI Checks

on:
  pull_request:
  push:
    branches:
      - main
      - next

concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  commit-lint:
    name: Lint commits
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: denoland/setup-deno@v1
        with:
          deno-version: "~1.31"
      - name: Install package dependencies
        run: npm ci
      - name: Run commitlint
        uses: wagoid/commitlint-github-action@v5
  lint:
    name: Lint code
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: denoland/setup-deno@v1
        with:
          deno-version: "~1.31"
      - name: Install package dependencies
        run: npm ci
      - name: Run Lint
        run: deno lint
  release:
    name: Release
    runs-on: ubuntu-22.04
    if: github.ref == 'refs/heads/main'
    environment: release
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: denoland/setup-deno@v1
        with:
          deno-version: "~1.31"
      - name: Versions
        run: |
          deno --version
          git --version
      # - name: Install package dependencies
      #   run: npm ci
      # - name: Release
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   run: npx semantic-release
